# Generated by Django 2.2.5 on 2020-01-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content1',
            field=models.TextField(default='dd'),
            preserve_default=False,
        ),
    ]
