# Generated by Django 2.2.5 on 2020-01-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200122_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_of_brith',
            field=models.DateTimeField(default='1980-01-26 12:09:58', verbose_name='Date'),
        ),
    ]
